# Site settings
title: SCVO | Digital Participation
description: We think the internet should be for everyone, so we're leading an ambitious programme to promote digital participation and basic online skills.
url: "http://digital.scvo.org.uk"
permalink: /blog/:title/

# Account settings
twitter: scvotweet
facebook: 509241123
ganalytics: UA-3467930-7

# Build settings
markdown: kramdown
